name: Deployment

on:
  workflow_call:
    inputs:
      registry:
        default: xnxktech.tencentcloudcr.com
        type: string
        required: false
      environment:
        default: Production
        description: The environment to use for the Production.
        type: string
        required: false
      environment_url:
        default: https://prod.example.com
        description: The URL to use for the Production.
        type: string
        required: false
      namespace:
        default: default
        description: The namespace of deployment
        type: string
        required: false
      repository:
        description: the image repository name.
        type: string
        required: true
    secrets:
      K8S_CONFIG:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  deploy:
    name: Kubernetes
    if: ${{ github.event_name != 'pull_request' }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Login Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Split Version or Branch
        uses: jungwinter/split@v2
        id: split
        with:
          separator: '/'
          msg: ${{ github.ref }}

      - name: Checkout ${{ steps.split.outputs._2 }}
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.split.outputs._2 }}

      - name: Setup repo name to lowercase
        id: reponame
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Split repo name
        uses: jungwinter/split@v2
        id: split_reponame
        with:
          separator: '/'
          msg: ${{ steps.reponame.outputs.lowercase }}

      - name: Setup Deployments to Production
        uses: starubiquitous/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
        with:
          args: --insecure-skip-tls-verify set image deployment/${{ steps.split_reponame.outputs._1 }} ${{ steps.split_reponame.outputs._1 }}=${{ inputs.REGISTRY }}/${{ inputs.repository }}:${{ steps.split.outputs._2 }} -n=${{ inputs.namespace }}

      - name: Restart Deployment
        uses: starubiquitous/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
        with:
          args: --insecure-skip-tls-verify rollout restart deployment/${{ steps.split_reponame.outputs._1 }} -n=${{ inputs.namespace }}
