name: Production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Kubernetes
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      environment: Production
      registry: registry.cn-hangzhou.aliyuncs.com
      namespace: myweb
      repository: lain-txl/laravel-app
    secrets:
      K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
